### PR TITLE
Sentry usage

### PR DESCRIPTION
**Pull request by sjaanus**
First version ready for usage. #117 

Tracks 3 parts at the moment:

1. Errors in main process
2. Errors in rendered process
3. Some errors related to signalR hubs

Lacks support for occasional errors that are in the belly of the beast, for example errors related to WebSocketTransport.js

### CODE REVIEW

**Comment by viktorgullmark** [comment]
Got it. Try removing node_modules entirely and reinstalling, guess you've tried that already though.

**Comment by sjaanus** [comment]
Blocked at the moment by https://github.com/getsentry/sentry-electron/issues/150

There is workaround to use another library, which I tested kindof worked, but would like to use official one.

**Comment by viktorgullmark** [comment]
Alright. No rush, good work so far either way, hopefully they respond at the sentry repo!

**Comment by sjaanus** [comment]
Ok, had some time at weekend and finished this one also. Can merge now.

**Comment by sjaanus** [comment]
@viktorgullmark ready for merge

**Comment by viktorgullmark** [comment]
Looks great, merged it into master. Thanks for the contribution yet again! @sjaanus

**Pull request merged**
