### PR TITLE
Created an for user to choose days how much back he wants to see history in graph

### PR DESCRIPTION
**Pull request by sjaanus**

### CODE REVIEW

**Comment by viktorgullmark** [comment]
Great work! I'm making some small tweaks to this. 

1. I'll include a check for undefined when fetching the setting, and will set a default value if this is undefined. This is poorly handled by our settings-service today, and we should add better handling of default-values. Right now it's quite some redundancy to get this to work properly.

2. I don't understand why the check for "this.isSummary" was removed. Can you explain the reason for this so that I'm not missing something? Otherwhise I'll go ahead and re-add it!

https://github.com/viktorgullmark/exilence/pull/113/commits/9a3fe56156046a3ebf26cfed6b83aa52dcefce21

**Comment by sjaanus** [comment]
2. It was because otherwise the chart update only works in group tab and not personal tab. 

I set 2 days and this is with the flag and shows whole history
image

This is without the flag, shows correctly, 2 days.
image

**Comment by viktorgullmark** [comment]
Thanks for the info @sjaanus. 0.9.8 has that check included, seems to work properly from what I can tell, great work!

**Comment by sjaanus** [comment]
For me I can see that in 0.9.8, the check is not included, and its working properly.

https://github.com/viktorgullmark/exilence/blob/master/ExilenceClient/src/app/authorize/components/income/income.component.ts

**Comment by viktorgullmark** [comment]
Oh yea, I meant excluded, my bad ^^

**Pull request merged**
