### PR TITLE
Implemented LZ4 

### PR DESCRIPTION
**Pull request by valseria**
Compression and decompression of json string data is now handled by the LZ4 algorithm

### CODE REVIEW

**Comment by petterannerwall** [comment]
Thank you for this!

The code itself looks good but we cannot merge this without fixing the compression on the client as well. With the current changes we will still send gzip encoded json from the client but try to decode it with lz4 in the backend. 

This can either be solved by continue to use gzip on client and restoring the old methods or change the compression on the client aswell.

**Comment by valseria** [comment]
Got you, I had forgotten about the client side change. 
Will update my fork to use LZ4 on the client and update the PR after work tonight.

**Comment by valseria** [comment]
For the front end, using this guy:
https://github.com/pierrec/node-lz4

Under [usage](https://github.com/pierrec/node-lz4#usage), which would better suit you? 
Synchronous or asynchronous?

**Comment by viktorgullmark** [comment]
@valseria Sorry for the late reply. You're right that asynchronous would be the way to go, we don't want to hog the thread at any point with synchronous calls.

**Comment by viktorgullmark** [comment]
Make sure to update your local branch from master before requesting the merge btw, otherwhise there'll be many conflicts to resolve, just a heads up! Great work so far

**Comment by valseria** [comment]
Closing PR as to resolve conflicts. New PR to follow. Sorry, this was preemptive.

**Pull request closed without merging**
